name: my_cobra_plugin_ios
description: iOS implementation of the my_cobra_plugin plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

flutter:
  plugin:
    implements: my_cobra_plugin
    platforms:
      ios:
        pluginClass: MyCobraPluginPlugin
        dartPluginClass: MyCobraPluginIOS

dependencies:
  flutter:
    sdk: flutter
  my_cobra_plugin_platform_interface:
    path: ../my_cobra_plugin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
